### ISSUE TITLE
The County tab now renamed to Region is displaying subcounties

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#17]
Health is devolved across the 47 counties in Kenya, hence   this field should only contain 50 items max for it to be usable.  This field should only pick the counties.

We have   hundreds of sub counties, thus including them here is not helpful

**Comment by ashaban** [comment]
I have added a fix but it will require reindexing, i will reindex tonight while no one is using the system

**Comment by cloehr651** [comment]
@lkwirica Can you please review the fix that Ally has made and confirm whether it is working correctly now?

**Comment by cloehr651** [comment]
@lkwirica  Can you please review the fix that Ally has made and confirm whether it is working correctly now?

**Comment by njugunask** [comment]
Regions need to be dropped so as to remain with the Counties only. (Eastern, Central, Nyanza, Coast, Western, RiftValley)

**Comment by lkwirica** [comment]
Dear Stanley,

These issues were closed in February. Please review only OPEN issues.

***@***.***D762AC.2CD2FA00]


Kind regards,

Loise Kwirica | HRIS Officer
HRH Kenya Mechanism
USAID Partner

IntraHealth International<http://www.intrahealth.org/> | Because Health Workers Save Lives.
P.O. Box 66726 - 00800
Ring Road/Lower Kabete Rd, Westlands, Nairobi, Kenya
9 West Building, 4th Floor,
t. +254 (020) 3645000 | m. +254 (0729) 097511
Email: ***@***.******@***.***>

***@***.***D762AC.2CD2FA00]

“If we have data, let’s look at data. If all we have are opinions, let’s go with mine .” — Jim Barksdale

**Comment by lkwirica** [comment]
Dear Loise,

Thanks, this is noted. The issues should then be moved to the '*Done*'
folder to avoid confusion.

Best,

Stanley.
