### ISSUE TITLE
More Details/Info Required on these issues

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#18]
If we are syncing contacts from Rapidpro, onto mHERO,   does this mean that the contact will have no fields i.e. designation, county   etc?     

Also, what happens when we update the phone details on iHRIS for a contact   existing on mHero (who was synced from Rapid pro) especially since the phone   numbers are captured in different formats...Doesn't this mean we will have   duplicate records for the HCW?   

What is the frequency of updating the record information on mHero once   updates are made on iHRIS e.g. change of designation, change of phone number   etc. both for existing contacts on mHero and new contacts on mHero? e.g.if a   record is cleaned on iHRIS and there is a duplicate on mHero, what is   captured?

**Comment by ashaban** [comment]
@lkwirica 
Yes, contacts originally added in rapidpro which then pushed to iHRIS 5 wont have other fields, they will just have phone numbers, names and contact groups.

Yes, contacts originally added from rapidpro and then later on get added into iHRIS 4, they will create 2 different records in iHRIS 5. This is the current setup.

Data is synchronized between systems after every 15 minutes.

**Comment by cloehr651** [comment]
@lkwirica can you confirm whether your questions have been adequately responded to by Ally?

**Comment by cloehr651** [comment]
@lkwirica can you please confirm whether your questions have been responded to by Ally?

**Comment by njugunask** [comment]
@lkwirica, move this item to the 'Done' folder

**Comment by lkwirica** [comment]
Dear Stanley,

These issues were closed in February. Please review only OPEN issues.

***@***.***D762AC.1D4BE8D0]

Kind regards,

Loise Kwirica | HRIS Officer
HRH Kenya Mechanism
USAID Partner

IntraHealth International<http://www.intrahealth.org/> | Because Health Workers Save Lives.
P.O. Box 66726 - 00800
Ring Road/Lower Kabete Rd, Westlands, Nairobi, Kenya
9 West Building, 4th Floor,
t. +254 (020) 3645000 | m. +254 (0729) 097511
Email: ***@***.******@***.***>

***@***.***D762AC.1D4BE8D0]

“If we have data, let’s look at data. If all we have are opinions, let’s go with mine .” — Jim Barksdale
