### ISSUE TITLE
Deleting/Removing records from mHero

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#19]
If contacts have been synced from Rapid pro to mHero, do we have a option to bulk remove them from the platform e.g. remove an entire group. This is important, given that groups deleted on Rapidpro are still existing on mHero, test groups on Rapidpro etc

There is also an issue of HCWs who may opt out and thereby need to be removed from the platform

**Comment by ashaban** [comment]
@lkwirica this feature is not yet supported, we can add it on the todo list.

CC @cloehr651

**Comment by cloehr651** [comment]
@lkwirica can you clarify whether you want to remove contacts or groups or both?

If you want to remove contacts (when they opt out or for whatever other reason), I'm guessing you just want them to not show up in mHero but if there is a record in iHRIS that will not be deleted - is that correct? @ashaban, if they don't have a record in iHRIS and were only added to RapidPro/mHero, would there no longer be any record of this contact?

**Comment by njugunask** [comment]
Hi Caitlin,

This issue was addressed, script developed and used for deleting/removing
records from mHero:- closed.

Best,

Stanley.

**Comment by cloehr651** [comment]
Thank you, Stanley, for confirming. In the future you can mark it as closed yourself.

**Comment by njugunask** [comment]
Okay, noted with thanks.
