### ISSUE TITLE
Delete CHV 1 and 2 groups from rapidpro only

### ISSUE THREAD

**Issue by ashaban** [intrahealth/emNutt#27]
Delete CHV 1 and 2 groups from rapidpro only

**Comment by ashaban** [comment]
No need to delete after adding ability to exclude records when wending messages.

**Comment by cloehr651** [comment]
@lkwirica and @njugunask, can you confirm whether this issue has been resolved? If so, move it to the "Done" column in the project (this can also be done under the "Projects" section of the bar on the right side - click on "In Review" and you can move it to "Done")
