### ISSUE TITLE
Ability to receive messages from HCWs on mhero

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#29]
mHero  (Rapid-pro) is not displaying incoming messages. The messages are received on the Telcos side but not on mhero.

Two way messaging cannot be achieved as such.

**Comment by cloehr651** [comment]
Mathew's feedback: The messages are not being received on the platform(s). Neither Rapidpro nor mHero, a quick test reveals that the messages are received on Africastalking but not on mHero/Rapidpro

**Comment by ashaban** [comment]
This is fixed, @lkwirica please confirm if its working and close this ticket

**Comment by lkwirica** [comment]
![image](https://user-images.githubusercontent.com/77771356/109832183-2cc16880-7c51-11eb-96d9-68492f3985bc.png)
I've sent this message- it's received in Africastalking but not on Rapidpro. 
Please troubleshoot

**Comment by ashaban** [comment]
This is working @lkwirica

**Comment by cloehr651** [comment]
@lkwirica do you need more info on this issue or can we close it?

**Comment by lkwirica** [comment]
This issue was resolved
