### ISSUE TITLE
Info. Required

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#30]
What is the difference between Failed and Ignored and the implication of each
![image](https://user-images.githubusercontent.com/77771356/108984599-235c5d00-76a1-11eb-9551-471c567844bf.png)

**Comment by ashaban** [comment]
- If two records shares same phone number, a message will be sent to one record and the other one will be ignored and placed to the ignored tab
- if a message fails to be sent it will be placed to the failed tab.

**Comment by cloehr651** [comment]
@lkwirica @njugunask is this clear to you now?

**Comment by lkwirica** [comment]
@cloehr651 , this is clear
