### ISSUE TITLE
Ability to Add non HCWs Contacts on mHero

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#33]
We need to include non HCWs on the mHero platform e.g. HRH committee members, Covid 19 committee members, HRH -Kenya Staff etc.
This may be handled the 'Add Person Feature' once it is rolled out

**Comment by ashaban** [comment]
Add person feature is already working, please have a look

**Comment by lkwirica** [comment]
I've added a new contact and it was saved, I believe after 15 min or so, it will be available for sending messages

**Comment by cloehr651** [comment]
@lkwirica and @ashaban do we need to create other "positions" for the contacts that are not health workers or we can just not fill in the position field and instead identify them in a group?

**Comment by njugunask** [comment]
Grouping contacts to particular groups is possible. This can be done through the 'Contact Group' Tab where a contact can be selected and assigned a group of choice. @lkwirica, was your requirement to add this feature be available so as to add a new contact assign it from a drop-down list of the groups available? Otherwise, if not this issue needs to be closed.

**Comment by lkwirica** [comment]
issue 33 is '**Ability to Add non HCWs Contacts on mHero "** We need to include non HCWs on the mHero platform e.g. HRH committee members, Covid 19 committee members, HRH -Kenya Staff etc.

For example, I've tried to add a new contact to the platform under the 'Add Person' feature. The 'Save' button is not active. Once the details about the person are keyed in, it cannot be saved.

**Comment by njugunask** [comment]
@Ally, it is not possible to save a new contact as raised above

**Comment by ashaban** [comment]
When was the last time you tried it?

**Comment by njugunask** [comment]
Hi Ally,

This morning, before you run the updates.

**Comment by njugunask** [comment]
This issue has been sorted out. able to add a contact and save it. Close issue.

**Comment by lkwirica** [comment]
Contacts added on this feature are NOT available for sending messages. This is pending

**Comment by ashaban** [comment]
@lkwirica now you should be able to see them into the sending messages page. Please test

**Comment by njugunask** [comment]
"@lkwirica and @ashaban do we need to create other "positions" for the contacts that are not health workers or we can just not fill in the position field and instead identify them in a group?"

The above suggestion by Caitlin of creating a group or groups for specific categories as raised by @lkwirica **(**Ability to Add non HCWs Contacts on mHero**)** hence assigning records to the specific category should be able to solve this issue.

**Comment by njugunask** [comment]
@lkwirica raised > "Contacts added on this feature are NOT available for sending messages. This is pending"

Searched a record I added yesterday and another one last week and contacts are not available.

**Comment by lkwirica** [comment]
A contact can be added on the platform but it is not yet possible to send the contact added a message.  Track the pending issues under #31
