### ISSUE TITLE
Add Person- Make phone number field required

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#34]
On the platform, job titles are pulled from iHRIS, we may need to either make the field not required or introduce a category for ‘other’. The category ‘other’ however, cannot exist in iHRIS to avoid errors in reporting.

**Comment by ashaban** [comment]
I have made job titles not required

**Comment by cloehr651** [comment]
@lkwirica , is this issue addressed now?

**Comment by lkwirica** [comment]
@cloehr651 The requirement of all fields has been removed. The phone number field should be required to avoid saving with no phone number added.

**Comment by cloehr651** [comment]
For the purposes of contact management, you may want to include either job title or cadre (even if the contacts are not HWs). You can certainly use contact groups that may indicate the cadre or other characteristic of the contact but having job title or cadre will prevent mHero users from having to guess as to who a contact is when they see just a name and phone number in the table of contacts, or when adding contacts to a group the user will have a bit more of an idea as to which contact group to add contacts.

**Comment by ashaban** [comment]
@lkwirica Phone number is now a required field

**Comment by cloehr651** [comment]
@lkwirica can we fully close this?

**Comment by lkwirica** [comment]
We cannot fully close this issue- The Residence is still a required field.

**Comment by cloehr651** [comment]
The phone number field issue has been resolved so this will be closed. I will leave the other Add Person issue active.
