### ISSUE TITLE
Failed Messages Folder

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#35]
Generate a failed list for the HCWs to whom the messages fail to send i.e. Failed Box such as inbox, to make possible to interrogate the cause of failure e.g. rectify the contact, obtain an updated contact etc. The current failed messages are not hitting Rapid pro Failed folder

**Comment by cloehr651** [comment]
Please see the [reports mock up](https://drive.google.com/file/d/14K9HAa_9oq74bzkJcX3mQBrosl3GAxw-/view?usp=sharing) that I requested you review. Does the Outbox and Sent tab fulfill your needs?

**Comment by lkwirica** [comment]
@cloehr651 I will review the mock up reports. However, this issue seems to relate to issue #40

**Comment by cloehr651** [comment]
@ashaban it seems like this could be displayed in the Flow Run breakdown and Message Sending Breakdown reports - in the status filter but "failed" doesn't show up as an option. Is that where you were planning to add this or as a separate report?

**Comment by njugunask** [comment]
@Ally, does ‘**completed**’ and ‘**entered in error**’ mean ‘**sent**’ and ‘**failed**’ respectively in the message sending breakdown?

**Comment by ashaban** [comment]
yes.

**Comment by njugunask** [comment]
Thanks, Ally. 
This issue needs to be closed.
