### ISSUE TITLE
Block Contacts who opt out of receiving messages

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#36]
Ability to block a contact who completely opts out of the platform. Exclude could work but it’s not feasible to keep remembering the list of those who’ve opted out each time you need to send a message in order to exclude them. We require a separate feature to handle this.

**Comment by ashaban** [comment]
@lkwirica this is done. I have added a UI to block contacts from receiving messages, the UI is accessible under mHero/Block Contacts. I have also added a report to show all blocked practitioners.
