### ISSUE TITLE
Contact Groups-Not All Groups are displayed

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#37]
The contact groups tab is not displaying all groups. Only 7 of 20 groups are displayed. If one attempts to subscribe HCWs to a particular group, the subscription is successful but on filtering with the specific group, nothing is displayed.

**Comment by ashaban** [comment]
where do you see those 20 groups? i only see 9 groups in rapidpro. i also see new group created in mhero with name 'jnjnjnj' and i can see 2 records subscribed on it

**Comment by lkwirica** [comment]
All groups are now visible after the syncing of contacts. This issue is resolved.
