### ISSUE TITLE
Discrepancy in total message counts in summary pop-up, AfricasTalking, and RapidPro

### ISSUE THREAD

**Issue by cloehr651** [intrahealth/emNutt#40]
Feedback from Mathew: as analysed from the messages sent last week, the stats shown are incorrect as they differ with the actual messages sent on AFricastalking as well as the Rapidpro Failed Box(It was empty). This is one of the issues recorded on the tracker.

**Comment by lkwirica** [comment]
Closing this issue to track all discrepancies issues in issue #48

**Comment by lkwirica** [comment]
This can be closed, and we can track discrepancy matters in issue #48
