### ISSUE TITLE
Mandatory fields for adding and editing new person

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#43]
If one adds an contact, and erroneously forgets to indicate the mobile contact, on editing, the platform requires one to add a residence. 

The  only mandatory fields should be:

- First Name
- Surname
- Mobile contact

**Comment by cloehr651** [comment]
For the purposes of contact management, you may want to include either job title or cadre (even if the contacts are not HWs). You can certainly use contact groups that may indicate the cadre or other characteristic of the contact but having job title or cadre will prevent mHero users from having to guess as to who a contact is when they see just a name and phone number in the table of contacts, or when adding contacts to a group the user will have a bit more of an idea as to which contact group to add contacts.

**Comment by ashaban** [comment]
@lkwirica this has been addressed, please confirm if its fixed.

**Comment by lkwirica** [comment]
Same as issue #31 #34

**Comment by cloehr651** [comment]
@lkwirica can you confirm if this has been fixed?

**Comment by cloehr651** [comment]
Linked to issue #56

**Comment by njugunask** [comment]
Mandatory fields have been captured. The issue needs to be closed.
