### ISSUE TITLE
Contacts without Names

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#44]
![image](https://user-images.githubusercontent.com/77771356/109583648-4360a600-7b11-11eb-9510-15fb97925447.png)
We have some contacts in the database without names e.g attached.

**Comment by lkwirica** [comment]
![Uploading image.png…]()

**Comment by ashaban** [comment]
@lkwirica i have scnned mhero and found some records without names, i tried to followup with one record that has a phone number 0721746296, this record is in iHRIS 4 and it has no names at all. to see this record please follow this link http://ihris.or.ke/moh/index.php/view?id=person%7C1129328
You clean this records, mHero will also be cleaned automatically.

Something to note, most of the issues related to data cleaning are originating in either iHRIS 4 or rapidpro (for those records uploaded to rapidpro and synced to iHRIS 5). iHRIS 5 is just a mirror of the data in iHRIS 4, if the data in iHRIS 4 is not clean, even the data in iHRIS 5 wont be clean
If you edit these records in iHRIS 4, then iHRIS 5 will be updated automatically.

I went ahead and scanned the whole iHRIS 4 database to identify records without names and found 18 records with such an issue as listed below
http://ihris.or.ke/moh/index.php/view?id=person%7C1129328
http://ihris.or.ke/moh/index.php/view?id=person%7C1130129
http://ihris.or.ke/moh/index.php/view?id=person%7C1133495
http://ihris.or.ke/moh/index.php/view?id=person%7C1133585
http://ihris.or.ke/moh/index.php/view?id=person%7C1133587
http://ihris.or.ke/moh/index.php/view?id=person%7C1134091
http://ihris.or.ke/moh/index.php/view?id=person%7C1134318
http://ihris.or.ke/moh/index.php/view?id=person%7C1134692
http://ihris.or.ke/moh/index.php/view?id=person%7C1139296
http://ihris.or.ke/moh/index.php/view?id=person%7C1139624
http://ihris.or.ke/moh/index.php/view?id=person%7C1140857
http://ihris.or.ke/moh/index.php/view?id=person%7C1141548
http://ihris.or.ke/moh/index.php/view?id=person%7C1141602
http://ihris.or.ke/moh/index.php/view?id=person%7C1145973
http://ihris.or.ke/moh/index.php/view?id=person%7C1146194
http://ihris.or.ke/moh/index.php/view?id=person%7C1146413
http://ihris.or.ke/moh/index.php/view?id=person%7C1146622
http://ihris.or.ke/moh/index.php/view?id=person%7C1155765

**Comment by cloehr651** [comment]
@lkwirica can we close this or do you want to wait until you have finished cleaning the records?

**Comment by ashaban** [comment]
@lkwirica please close this issue

**Comment by njugunask** [comment]
Data cleaning of contacts in iHRIS will help resolve this issue. Issue needs to be closed
