### ISSUE TITLE
Contacts sharing a phone number-stored together

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#45]
![image](https://user-images.githubusercontent.com/77771356/109583878-a81c0080-7b11-11eb-8f73-4bd1797385a7.png)
We have instances of 2 contacts sharing one phone number  and stored as one contact

**Comment by ashaban** [comment]
@lkwirica this record was originally added in rapidpro and then syncronized to iHRIS 5. The names were not merged in iHRIS, that is how it was added in iHRIS from rapiodpro. Here is a link to the reocrd in rapidpro http://ihris.or.ke:8000/contact/read/9497a497-c077-4320-95df-6256d4fc9b6e/
Just rename the name properly. Im closing this issue.

**Comment by cloehr651** [comment]
@lkwirica can you confirm that this can be fully closed?

**Comment by njugunask** [comment]
Telephone contact in iHRIS and RapidPro for this record is different, needs to be updated accordingly. Issue can be closed.

**Comment by lkwirica** [comment]
This issue was closed in March.

***@***.***D762A9.D6FBCBE0]
