### ISSUE TITLE
Mismatching report names

### ISSUE THREAD

**Issue by cloehr651** [intrahealth/emNutt#49]
In the reports section the name is: Workflows Overview; once you click on the report the name is: mHero Flow Summary (I suggest using Flows Overview or Flows Summary)
In the reports section the name is: Flow Run Breakdown; once you click on the report the name is: Flow Run by Practitioner (I suggest keeping Flow Run Breakdown)
In the reports section the name is: Message Sending Breakdown; once you click on the report the name is: Message Sending by Practitioner (I suggest keeping Message Sending Breakdown)
In the reports section the name is: Message Exchange; once you click on the report the name is: mHero Message Exchange (we can keep the version without mHero in the name)

**Comment by ashaban** [comment]
@cloehr651 this is fixed

**Comment by cloehr651** [comment]
Thanks @ashaban !
