### ISSUE TITLE
Unable to add and edit certain fields in records created within the module

### ISSUE THREAD

**Issue by cloehr651** [intrahealth/emNutt#56]
When adding a new contact it is possible to specify their position but nothing about their facility, county, and cadre. However if you try to add a person with the blue "Add iHRIS Practitioner" button the position fields are not there. Then when editing a person that was added via the module, it is not possible to edit the position information.

**Comment by cloehr651** [comment]
Related to #43

**Comment by ashaban** [comment]
@lkwirica please review this and close

**Comment by njugunask** [comment]
It is still not possible to specify/add a new contact **County** and **Cadre** in the module. It is also not possible to edit the position field

**Comment by ashaban** [comment]
@njugunask A contact is assigned a Position (this is possible), a position has a facility and cadre on it. A facility is also attached to a specific county. So what you need is just to assign a position to a contact and that will automatically assign cadre, county etc. It is possible to edit a position, just go to the search position and click a respective position, then click edit and start editing the details of the position, including facility, job (cadre is defined in job)

**Comment by njugunask** [comment]
Sure, I have reviewed the Position tab as advised and caters also for county and cadre. However, one issue which seems to affect searching records with both names not possible. As you fix #60, implement the same here.

**Comment by ashaban** [comment]
@njugunask lets track the issue for searching two names on #60. If you can add new record and edit them please close this issue.

**Comment by njugunask** [comment]
@cloehr651 close this issue
