### ISSUE TITLE
Bug in records displaying in Search People table

### ISSUE THREAD

**Issue by cloehr651** [intrahealth/emNutt#57]
It looks like only 21 records have been added when you first view the Search People table but if you click to go to the 2nd page of records it then shows that there are 122,013 records in the table and when you get to the third page of results it looks like there are lots of duplicates. If you change the number of rows when on the first page this issue does not appear - it only displays 21 rows.
![Screen Shot 2021-05-06 at 15 18 49](https://user-images.githubusercontent.com/57463652/117353901-baeae280-ae7e-11eb-934d-60f79047af44.png)
![Screen Shot 2021-05-06 at 15 18 59](https://user-images.githubusercontent.com/57463652/117353904-bb837900-ae7e-11eb-981d-9ffa0a6f58a1.png)
![Screen Shot 2021-05-06 at 15 19 11](https://user-images.githubusercontent.com/57463652/117353905-bb837900-ae7e-11eb-8ebf-99d67fbe6c9a.png)

**Comment by njugunask** [comment]
This issue has been resolved. Displaying a consistent number, i.e. 122,878
Close issue.
