### ISSUE TITLE
Scheduling Messages feature is not working

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#58]
![image](https://user-images.githubusercontent.com/77771356/121320048-7aff9b00-c915-11eb-971e-09b942644fc1.png)
On attempting to schedule a message, the page hangs while displaying' sending request'

**Comment by cloehr651** [comment]
Can you please clarify whether this has happened multiple times or just once? If you tried it multiple times was there any difference in the request (number of recipients, flow vs message, etc.)?

**Comment by lkwirica** [comment]
Multiple attempts, no success. Same no. of recipients as usual.

This was working previously.

**Comment by njugunask** [comment]
Hi Kwirica, this feature is working okay see below.
<img width="932" alt="Scheduled mgs1" src="https://user-images.githubusercontent.com/77440202/121707633-6d960c80-cadf-11eb-85b8-ec0dc2dedeaf.png">
<img width="940" alt="Scheduled mgs2" src="https://user-images.githubusercontent.com/77440202/121707638-6ec73980-cadf-11eb-8dea-a726886dfb0c.png">
<img width="937" alt="Scheduled mgs3" src="https://user-images.githubusercontent.com/77440202/121707641-6f5fd000-cadf-11eb-93c2-20a97c328e23.png">

**Comment by lkwirica** [comment]
This feature is still not working... Scheduled a message for 3:22 PM on 14th June...
A yellow message box popped up 'This process is taking some time...server is sending messages... 
No message was sent out, at the scheduled time.

**Comment by lkwirica** [comment]
![image](https://user-images.githubusercontent.com/77771356/121948281-b78d2580-cd5f-11eb-9814-a00f7038d8d2.png)
This feature is still not working... Scheduled a message for 3:22 PM on 14th June...
A yellow message box popped up 'This process is taking some time...server is sending messages...
No message was sent out, at the scheduled time.

**Comment by ashaban** [comment]
This issue is fixed @lkwirica

**Comment by njugunask** [comment]
@lkwirica, are you able to schedule messages for sending out and verify if you are encountering the same problem?

**Comment by lkwirica** [comment]
Message scheduled for 20th June was sent out.
