### ISSUE TITLE
Bug in Search People table 

### ISSUE THREAD

**Issue by njugunask** [intrahealth/emNutt#61]
The search people table only displays records on
<img width="948" alt="Search People Pg1" src="https://user-images.githubusercontent.com/77440202/122517923-45476a00-d019-11eb-8eb3-e55930712582.png">
<img width="956" alt="Search People Pg2" src="https://user-images.githubusercontent.com/77440202/122517930-47112d80-d019-11eb-9aa8-14d0f71e9d65.png">
<img width="955" alt="Search People Pg3" src="https://user-images.githubusercontent.com/77440202/122517931-47112d80-d019-11eb-83a9-ee04ff5c4b72.png">
 the first page. the next pages are blank

**Comment by ashaban** [comment]
@njugunask this is fixed
