### ISSUE TITLE
Over 500 blank records on the platform- Send Messages

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#65]
![image](https://user-images.githubusercontent.com/77771356/122707817-787d3980-d263-11eb-973d-894444c50993.png)
There are over 500 blank contacts on the platform. @ashaban I believe these are contacts pulled from the 'Add Person' feature, that are being displayed without names.

**Comment by ashaban** [comment]
@lkwirica this is already fixed and Stanley reported the same issue on #61

**Comment by lkwirica** [comment]
@ashaban check screenshot done a few minutes ago...
Contacts 1-500+ on the platform are still displaying blank names

**Comment by lkwirica** [comment]
This bug is on send messages not search people

**Comment by ashaban** [comment]
@lkwirica  Sorry, i thought this was for the search people, this is resolved now. Please check.

**Comment by njugunask** [comment]
@lkwirica, this issue has been fixed.

**Comment by njugunask** [comment]
@lkwirica, move this closed issue to 'done' folder
