### ISSUE TITLE
Duplicate records being added using the 'Add Person' feature

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#66]
While iHRIS controls for duplicates using ID number, the Add Person feature allows users to create new records for existing users on the platform. 
Can we control this with phone number i.e. before adding a person, the system checks for existing phone number on the platform. 

Without controls, it seems one record can be added severally
![image](https://user-images.githubusercontent.com/77771356/123023967-0468a000-d3e1-11eb-8b28-c8f89459fc66.png)

**Comment by ashaban** [comment]
This is fixed, please review.

**Comment by njugunask** [comment]
This issue has been resolved, it can be closed. @lkwirica, please confirm and action.
