### ISSUE TITLE
On the Add Person feature- Enforce the cadre field...Include the option of 'OTHER'

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#69]

**Comment by ashaban** [comment]
@lkwirica this is done, please review

**Comment by njugunask** [comment]
The field for 'Cadre' is now enforced under the position section. @lkwirica confirm and close.

**Comment by lkwirica** [comment]
@ashaban I believe we've enforced 'Position Title' and not 'Cadre'...

Does this mean there's also a cadre called 'Other' to which the position title 'Other' has been mapped? Because the purpose for this fix, is the output on the report. We only have 15 or so cadres but several position titles in iHRIS.

Can we just have the field 'Cadre'?

**Comment by ashaban** [comment]
I will explain to you on the call in 30 minutes, plan not to miss
