### ISSUE TITLE
Fixing bug with cancelling scheduled messages/flows

### ISSUE THREAD

**Issue by cloehr651** [intrahealth/emNutt#7]
The "Health Worker Health Snapshot - 19 Oct 2020" flow was scheduled to be sent out on a regular basis but scheduled sending was canceled in the 2nd week of December, however looking at RapidPro reveals that the flow is still being sent out. 

_From Ally: Every time emNutt is started, it also starts the scheduler service that loads all scheduled messages/flows. currently, cancelling a schedule doesn't remove it just cancel it from the database and doesnt refresh the scheduler service, the scheduler is refreshed only when emNutt is restarted. 

I have restarted emNutt, that means the scheduler has been refreshed and the message will not be sent out again. I will need to add ability to auto refresh the scheduler service every time a schedule is cancelled_ This also needs to be done in a way that it will behave this way for all instances.

**Comment by lkwirica** [comment]
![image](https://user-images.githubusercontent.com/77771356/105306842-65d7d900-5bcd-11eb-9707-628f117889f4.png)
There is an error on cancelling a schedule

**Comment by lkwirica** [comment]
![image](https://user-images.githubusercontent.com/77771356/105310762-51481080-5bce-11eb-8244-e4b0821d4d0d.png)
Also, control the scheduling of messages in the past e.g. scheduling messages to be sent at 2:00, at 10:00 am

**Comment by ashaban** [comment]
@lkwirica the error for cancelling schedules has been addressed.
