### ISSUE TITLE
The County Tab is missing

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#74]
@ashaban the County Tab is missing from the 'Send Messages'. 

This is a very important tab, without which, we cannot send the vaccination messages.

**Comment by lkwirica** [comment]
![image](https://user-images.githubusercontent.com/77771356/123978106-43da5200-d9c8-11eb-9463-e526d971d67c.png)

**Comment by ashaban** [comment]
@lkwirica the county tab is now added
![sendmsg](https://user-images.githubusercontent.com/3152817/124015828-b4479a00-d9ed-11eb-82d0-6a0b0ac98001.png)
